#!/bin/bash
#COPY LOGIND && SYSTEMCLOSE...
#yay dwm-git
#pacman -Suy xterm tmux xpdf thunar
#yay ibus-mozc
#yay opera
#yay megasync
#pacman -S networkmanager network-manager-applet
#pacman -S audacious
#pacman -S audacity
#pacman -S lxappearance pavucontrol
#pacman -S kodi filezilla scrot
#yay light-git
#yay visual-studio
#yay teamviewer
#cd slock 
#sudo make 
#sudo make clean
#sudo make install
#cd ..
#
sudo make 
sudo make clean
sudo make install
mkdir -p  ~/.config/dunst
cp dunstrc ~/.config/dunst/dunstrc
